
url = 'http://automationexercise.com'
review = 'some text for review'
message = 'text'
subject = 'test'
# variable for account
name = 'test_name'
email = 'test_email@email.com'
password = '1234test'
first_name = 'test_first'
last_name = 'test_last'
company = 'test_company'
address1 = 'test_address'
address2 = 'test_address'
state = 'test_state'
city = 'test_city'
zip = '12345'
number = '1234567890'
country = 'Canada'
name_card = 'Test Test'
cart_number = '0000000000000000'
cvc = '000'
exp_m = '01'
exp_y = '2033'